
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { Jost } from 'next/font/google'
import "./globals.css";
import Bothnav from './components/Bothnav/page'



const raleway_init = Raleway({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500'],
  style: 'normal',
  variable: '--font-raleway'
});

const jost_init = Jost({
  subsets: ['latin'],
  style: 'normal',
  weight: ['100', '200', '300', '400'],
  variable: '--font-young-sans'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway_init.variable} ${jost_init.variable} bg-hole_body relative`}>

        <Bothnav/>
        {children}

      </body>
    </html>
  );
}
